version: '3.1'
volumes:
  db-volume:

services:
  web:
    image: nginx:1.18
    ports:
      - 80:80
      - 88:88
  
    links:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  php:
    build: ./php
    volumes :
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      TZ: "Asia/Tokyo"
    volumes:
      - db-volume:/etc/mysql/

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=PASSWORD
